### ISSUE TITLE
Discovery failure for SingleExecution jobs

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/datasource-observer#11]
The latest 2.1.0 release causes an exception when trying to discover datasets for a SingleExecution job that should be executed immediately. Below you find an example for a exception causing job as well as an extract of the raised exception.
Job example:
```
{
	"areaOfInterest": {
		"extent": [
			6.918,
			51.0224,
			7.6176,
			51.3268
		]
	},
	"created": "",
	"description": "",
	"execution": {
		"event": {
			"eventType": "SingleJobExecutionEvent"
		},
		"startAt": null
	},
	"id": "",
	"inputs": [
		{
			"sourceType": "CopernicusSubsetDefinition",
			"identifier": "OPTICAL_IMAGES_SOURCES",
			"satellite": "sentinel-2",
			"productType": "L2A",
			"maximumCloudCoverage": 10
		}
	],
	"name": "Test",
	"processingTool": "de.hsbo.wacodis.vegetation_density_ndvi",
	"productCollection": "demo-vegetation-density-ndvi",
	"retrySettings": {
		"maxRetries": 1,
		"retryDelay_Millies": 500
	},
	"temporalCoverage": {
		"duration": "P1M"
	},
	"useCase": "",
	"executionSettings": {
		"executionMode": "all"
	}
}
```
Exception:
```
2021-01-06 07:58:33.583 DEBUG 1 --- [mmm7dpkoX6QWA-1] de.wacodis.observer.quartz.JobScheduler  : class java.lang.NullPointerException: null

java.lang.NullPointerException: null
        at de.wacodis.observer.core.WacodisJobConfiguration.computeTemporalCoverageStartDate(WacodisJobConfiguration.java:179) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.core.WacodisJobConfiguration.configureFirstDataQueryPeriod_singleExecutionJob(WacodisJobConfiguration.java:153) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.core.WacodisJobConfiguration.configureFirstDataQueryPeriod(WacodisJobConfiguration.java:54) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.core.JobFactory.initializeJobs(JobFactory.java:101) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.quartz.JobScheduler.generateQuartzJobDefinitions(JobScheduler.java:222) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.quartz.JobScheduler.scheduleJob(JobScheduler.java:52) ~[datasource-observer-core-2.1.0.jar!/:na]
        at de.wacodis.observer.listener.MessageListener.lambda$receiveNewJob$0(MessageListener.java:34) [datasource-observer-core-2.1.0.jar!/:na]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_275]
        at de.wacodis.observer.listener.MessageListener.receiveNewJob(MessageListener.java:33) [datasource-observer-core-2.1.0.jar!/:na]
```

**Comment by cDanowski** [comment]
Hi,

as I understood, for SingleExecutionEvents there is a mandatory parameter called "temporalCoverageEndDate". This is missing in your exmple request and hence leads to the NULL pointer exception.

By adding it to the request, the exception disappears.

```
{
	"areaOfInterest": {
		"extent": [
			6.918,
			51.0224,
			7.6176,
			51.3268
		]
	},
	"created": "",
	"description": "",
	"execution": {
		"event": {
			"eventType": "SingleJobExecutionEvent",
                        "temporalCoverageEndDate": "2020-12-01"
		},
		"startAt": null
	},
	"id": "",
	"inputs": [
		{
			"sourceType": "CopernicusSubsetDefinition",
			"identifier": "OPTICAL_IMAGES_SOURCES",
			"satellite": "sentinel-2",
			"productType": "L2A",
			"maximumCloudCoverage": 10
		}
	],
	"name": "Test",
	"processingTool": "de.hsbo.wacodis.vegetation_density_ndvi",
	"productCollection": "demo-vegetation-density-ndvi",
	"retrySettings": {
		"maxRetries": 1,
		"retryDelay_Millies": 500
	},
	"temporalCoverage": {
		"duration": "P1M"
	},
	"useCase": "",
	"executionSettings": {
		"executionMode": "all"
	}
}

```

@SebaDro , @arnevogt : So, to be certain, is it correct, that for SingleExecutionEvents the parameter "temporalCoverageEndDate" must be submitted? 
If so, then the issue can be closed directly and the parameter be added to the request.
If not, then the code must be changed indeed.

If mandatory,  that parameter check for SingleExecutionEvents can be integrated in the Job input check running in `WacodisJobValidator`

**Comment by SebaDro** [comment]
Hey, thanks for you reply.

Considering the `SingleJobExecutionEvent` model class within the datasource-observer module you are technically right. However, the models in this module should be consistent with those from the job-definition-api module, because the API solely should specify which parameters are mandatory or optional. If you have look on the `SingleJobExecutionEvent` model class within the job-definition-api you will not find a mandatory restriction on the `temproalCoverageEndDate`: https://github.com/WaCoDiS/job-definition-api/blob/5ceacfdc4dd91383ce9848501e0b18ab750a6ce5/src/main/java/de/wacodis/jobdefinition/model/SingleJobExecutionEvent.java#L24-L44

Despite the existence of such a restriction within the OpenAPI specifications, as far as I remember, we removed this restriction from the job-definition-api to ensure backwards compatibility. So, I would suggest to allow the absence of the `temproalCoverageEndDate` to be consistent with the job-definition-api. Maybe, it would be sufficient to assume a default value like `DateTime.now()` if the parameter is missing.

**Comment by arnevogt** [comment]
I suggest looking at the wacodis job's date of create instead of using _DateTime.now()_ as fallback if _temporalCoverageEnddate_ is not set.

**Comment by cDanowski** [comment]
Hi,

ah okay. I just applied your suggestion. It makes sense indeed, to have a fallback strategy here.

**Comment by cDanowski** [comment]
@arnevogt Even better. implemented that as well.
